resteasy:
  jaxrs:
    app:
      registration: auto
      classes: com.sample.app.configuration.JaxrsApplication, com.sample.app.configuration.DoubleJaxrsApplication
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - shutdown
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    org:
      springframework: info
